[package]
name = "voksel"
version = "0.1.0"
authors = ["Matteo Campanelli <matteo.campanelli@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#cpsnarks-set = { git = "https://github.com/matteocam/cpsnarks-set",  default-features = false }
bulletproofs = { git = "https://github.com/matteocam/bulletproofs", branch= "main", default-features = false }

